# Generated by Django 2.2.1 on 2019-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short name')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('unactive', 'unactive'), ('active', 'active'), ('maintenance', 'maintenance'), ('test', 'test'), ('waiting', 'waiting'), ('wintering', 'wintering'), ('moved', 'moved')], default='active', max_length=32, verbose_name='Status')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.IntegerField(verbose_name='Altitude')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Phone number')),
            ],
        ),
    ]
