# Generated by Django 2.2.1 on 2019-06-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winds_mobi_jdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('unactive', 'Unactive'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('test', 'Test'), ('waiting', 'Waiting'), ('wintering', 'Wintering'), ('moved', 'Moved')], default='active', max_length=32, verbose_name='Status'),
        ),
    ]
