version: '3.7'

services:
  postgres:
    image: postgres:9.3.24
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=winds_mobi
    networks:
      - winds.mobi
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

networks:
  winds.mobi:
    driver: bridge
