# Generated by Django 2.2.12 on 2020-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                ("id", models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name="Id")),
                ("short_name", models.CharField(max_length=20, verbose_name="Short name")),
                ("name", models.CharField(max_length=40, verbose_name="Name")),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                ("altitude", models.IntegerField(blank=True, null=True, verbose_name="Altitude")),
            ],
        ),
    ]
